import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to{" "}
          <Link as={"/about"} href="/about" prefetch={false}>
            Next.js!
          </Link>
        </h1>
        <h1 className={styles.title}>
          <Link
            prefetch={false}
            as="/product/[slug]"
            href={{
              pathname: "/product/[slug]",
              query: { slug: 1 },
            }}
          >
            Product Navigation
          </Link>
        </h1>
      </main>
    </div>
  );
}
